[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "crazy-rl"
description="Environments and learning code for doing (MOMA)RL with CrazyFlies."
readme = "README.md"
requires-python = ">= 3.8"
authors = [{ name = "Florian Felten & Pierre-Yves Houitte", email = "florian.felten@uni.lu" }]
license = { text = "MIT License" }
keywords = ["Reinforcement Learning", "Multi-Objective", "Multi-Agent", "RL", "AI", "gymnasium", "pettingzoo"]
classifiers = [
    "Development Status :: 4 - Beta",  # change to `5 - Production/Stable` when ready
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    'Intended Audience :: Science/Research',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
]
dependencies = [
    "mo-gymnasium >=0.3.3",
    "gymnasium >=0.27",
    "pettingzoo >=1.22.3",
    "numpy >=1.21.0",
    "torch >=1.11.0",
    "pygame >=2.1.0",
    "cflib",
    "wandb",
    "seaborn",
    "tensorboard",
    "stable-baselines3",
]
dynamic = ["version"]

[project.optional-dependencies]
# Update dependencies in `all` if any are added or removed
# OLS requires pycddlib and libgmp to be installed, which does not work on MacOS for now.

all = []
testing = ["pytest ==7.1.3"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["crazy_rl", "crazy_rl.*"]

[tool.setuptools.package-data]
crazy_rl = ["*.json", "assets/*"]

# Linting, testing, ... ########################################################
[tool.black]
safe = true
line-length = 127
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'

[tool.isort]
atomic = true
profile = "black"
src_paths = ["crazy_rl"]
extra_standard_library = ["typing_extensions"]
indent = 4
lines_after_imports = 2
multi_line_output = 3
